default:
  artifacts:
    expire_in: 1 day

stages:
  - deploy

deploy-production:
  stage: deploy

  image: alpine:latest

  before_script:
    - apk add --no-cache openssh-client

    - mkdir -p ~/.ssh
    - printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

  script:
    - |
      ssh ubuntu@$PRODUCTION_HOST << EOF

        set -e

        cd ~/lifeflow/deploy

        git pull

        docker login gitlab.lnu.se:5050 \
          -u "$REGISTRY_USER" \
          -p "$REGISTRY_PASSWORD"

        docker compose \
          -f docker-compose.yml \
          -f docker-compose.prod.yml \
          pull

        docker compose \
          -f docker-compose.yml \
          -f docker-compose.prod.yml \
          up -d --remove-orphans --wait

        docker image prune -f

      EOF

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
