services:
  backend:
    build:
      target: production

    expose:
      - "5000"

    restart: unless-stopped

  frontend:
    build:
      context: ../lifeflow-frontend/app

    ports:
      - "80:80"
      - "443:443"

    restart: unless-stopped

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
