services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27071:27071"

  backend:
    build:
      context: ../lifeflow-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/lifeflow
    depends_on:
      - mongo

  frontend:
    build:
      context: ../lifeflow-frontend/my-app
    depends_on:
      - backend
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  mongo_data:
  
