services:
  mongo:
    image: mongo:8.3

    restart: unless-stopped

    volumes:
      - mongo_data:/data/db

  backend:
    image: ghcr.io/fielifia/lifeflow-backend:latest
    pull_policy: always

    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - CLIENT_URLS=${CLIENT_URLS}

    env_file:
      - .env

    expose:
      - "5000"

    depends_on:
      - mongo

    restart: unless-stopped

  frontend:
    image: ghcr.io/fielifia/lifeflow-frontend:latest
    pull_policy: always

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - backend

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot

    restart: unless-stopped

volumes:
  mongo_data:
