services:
  backend:
    image: gitlab.lnu.se:5050/1dv613/student/sa226jf/workspace/lifeflow-backend:latest

    expose:
      - "5000"

    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}

  frontend:
    image: gitlab.lnu.se:5050/1dv613/student/sa226jf/workspace/lifeflow-frontend:latest

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
