services:
  mongo:
    image: mongo:8.3

    restart: unless-stopped

    volumes:
      - mongo_data:/data/db

  backend:
    environment:
      - MONGO_URI=${MONGO_URI}

    depends_on:
      - mongo

    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:5000/api/health').then(()=>process.exit(0)).catch(()=>process.exit(1))"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  frontend:
    depends_on:
      - backend

    restart: unless-stopped

volumes:
  mongo_data:
